### ISSUE TITLE
File path issue with add_experiment()

### ISSUE THREAD

**Issue by persalteas** [copasi/basico#9]
Hello,

When doing parameter estimation, one loads data with the add_experiment() function which takes a parameter "file_name" to chose a specific storage location for the preprocessed file.

If i want my model and experiment files to be in a subfolder compared to the current directory i am running my script in, i would typically do:
```
from basico import *
import pandas as pd

model_io.load_model("copasi\\example.cps")
data = pd.read_csv("copasi\\example.txt", header=0, sep='\t')
add_experiment("example", data, file_name="copasi\\exp_example.tsv")

result = run_parameter_estimation()   # raises file not found (from C code ?)
```
The experiment saving works fine, but when run_parameter_estimation() looks for the file, it looks at a wrong path:
```
ERROR:root:Error while initializing the simulation: >ERROR 2022-01-14T10:00:09<
  CFitting (8): Failure reading file 'C:/Users/lbecquey/Desktop/minimal_example/copasi/copasi/exp_example.tsv'.
```
Notice the duplicated name of the subfolder in the path.

Note that using an absolute path everywhere does not change the problem.

**Comment by persalteas** [comment]
If you need a minimal example files (just the above code) with model and data.
[minimal_example.zip](https://github.com/copasi/basico/files/7869253/minimal_example.zip)

**Comment by fbergmann** [comment]
thanks for letting me know, i'll issue another bugfix release for that.

**Comment by fbergmann** [comment]
I have just pushed a new version of basico to pypi that resolves the issue for me. The fix translates the path into an absolute one, and that resolves the issue for me. As for COPASI itself it always expects the experiment files relative to the COPASI file loaded. That is where the doubled folder name came from.

**Comment by persalteas** [comment]
Perfect, it works for me too. Thanks !

**Comment by persalteas** [comment]
Hi again,

The fix worked for the simple example above, however i still have the issue when i save and re-load the model for use with multiprocessing:

```
from basico import *
import pandas as pd
from multiprocessing import Pool, freeze_support

def wrapper(method):
    # This will be run in a new process, so you need to load the model again
    # (it cannot be passed as argument because it is not pickleable)
    model_io.load_model("copasi\\example_with_data.cps")
    run_parameter_estimation(method=method, update_model=False)

if __name__ == "__main__":

    freeze_support() # because i run on Windows

    model_io.load_model("copasi\\example.cps")
    data = pd.read_csv("copasi\\example.txt", header=0, sep='\t')
    add_experiment("example", data, file_name="copasi\\exp_example.tsv")
    model_io.save_model_and_data("copasi\\example_with_data.cps")

    # Spawn two processes and make them execute function wrapper() with 2 different arguments
    with Pool(processes=2) as p:
        p.map(wrapper, ["Steepest Descent", "Levenberg - Marquardt"])
```

Each process still looks for the file at a wrong path with a duplicated subfolder name.

```
ERROR:root:Error while initializing the simulation: >ERROR 2022-01-17T08:22:45<
  CFitting (8): Failure reading file 'C:/Users/lbecquey/Desktop/minimal_example/copasi/copasi/example.txt'.
ERROR:root:Error while initializing the simulation: >ERROR 2022-01-17T08:22:45<
  CFitting (8): Failure reading file 'C:/Users/lbecquey/Desktop/minimal_example/copasi/copasi/example.txt'.
```

I can see that the example_with_data.cps file, as saved by model_io.save_model_and_data(), contains the short path: `<Parameter name="File Name" type="file" value="copasi\exp_example.tsv"/>`. Maybe the absolute path should be stored there too ?

**Comment by fbergmann** [comment]
the workaround would be to use `save_model` right now (as your data files are in the right place already), it seems like an issue in `save_model_and_data`.

**Comment by fbergmann** [comment]
released on pypi as 0.11

**Comment by persalteas** [comment]
It works ! Thanks.
